# Generated by Django 4.2.3 on 2023-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_subscription_status',
            field=models.BooleanField(default=False),
        ),
    ]
