# Generated by Django 4.2.3 on 2023-08-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_stripecustomer_stripe_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_beginning_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
