# Generated by Django 4.2.3 on 2023-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_stripecustomer_subscription_beginning_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
