# Generated by Django 4.2.3 on 2023-08-30 14:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_headline_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='headline',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
