# Generated by Django 4.2.3 on 2023-08-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_image_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='compressed_image',
        ),
    ]
