# Generated by Django 4.2.3 on 2023-08-29 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool', '0004_remove_image_compressed_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageUpload',
        ),
    ]
