# Generated by Django 4.2.3 on 2023-08-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_rename_image_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='download_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
