# Generated by Django 4.2.3 on 2023-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_imageupload_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='anonymous_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
